services:
  - type: web
    name: getting-back
    env: ruby
    buildCommand: |
      npm install
      bundle install
      bundle exec rails assets:precompile
    startCommand: bundle exec rails server -p $PORT -e production
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: getting-back-db
          property: connectionString

databases:
  - name: getting-back-db
    databaseName: getting_back_production
    user: getting_back_user 