name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.8'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install
        yarn install --frozen-lockfile
    
    - name: Run tests
      run: |
        bundle exec rails test
        bundle exec rubocop

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Deploy to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        if [ -z "$RENDER_TOKEN" ] || [ -z "$RENDER_SERVICE_ID" ]; then
          echo "⚠️  RENDER_TOKEN or RENDER_SERVICE_ID not configured"
          echo "📝 Please configure these secrets in GitHub:"
          echo "   - RENDER_TOKEN: Your Render API token"
          echo "   - RENDER_SERVICE_ID: Your Render service ID"
          echo "🔗 Or configure Render to deploy automatically after CI passes"
          exit 0
        fi
        
        echo "🚀 Triggering Render deployment..."
        curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_TOKEN" \
          -H "Content-Type: application/json"
        
        if [ $? -eq 0 ]; then
          echo "✅ Deploy triggered successfully!"
        else
          echo "❌ Failed to trigger deploy"
          exit 1
        fi 